VPATH := $(dir $(abspath $(firstword $(MAKEFILE_LIST))))

TARGETNAME := RlGl
TARGET := lib$(TARGETNAME).so
INCFLAGS := $(addprefix -I,$(shell $(CC) -xc /dev/null -E -Wp,-v 2>&1 |sed -n 's,^ ,,p'))

OBJS := rlgl.o

INCLUDES_RLGL := \
								 rlgl_sdl.h

INCLUDES_RLGL_ALL := \
										 rlgl_sdl.h \
										 rlgl.h

CSPIG ?= $(shell command -v ClangSharpPInvokeGenerator)
ifeq ($(CSPIG),)
$(error ClangSharpPInvokeGenerator missing)
endif

SED ?= $(shell command -v sed)
ifeq ($(SED),)
$(error sed missing)
endif

PKGCONFIG ?= $(shell command -v pkg-config)

CFLAGS += -fPIC -fvisibility=hidden

CFLAGS += -DGRAPHICS_API_OPENGL_33
CFLAGS += -DBUILD_LIBTYPE_SHARED

ifneq ($(PKGCONFIG),)
LDLIBS += $(shell $(PKGCONFIG) --libs sdl2)
LDLIBS += $(shell $(PKGCONFIG) --libs glu)
else
LDLIBS += -lSDL2
LDLIBS += -lGLU -lGL
endif

CSPIGFLAGS += -x c -std c99 -c generate-macro-bindings -c compatible-codegen -D CS_CODEGEN

.PHONY: all
all: $(TARGET) RlGl.cs

RlGl.cs: $(INCLUDES_RLGL)
	$(CSPIG) $(CSPIGFLAGS) $(addprefix -t ,$(INCLUDES_RLGL_ALL)) $(addprefix -f ,$^) -o $@ -l $(TARGETNAME) -n RlGl $(INCFLAGS) ||:
	$(SED) -i \
		-e '/NativeType\w*("#define/d' \
		-e 's/\(^\s*\)\?\[\(\w*:\s*\)\?NativeType\w*("[^"]*")\]\s*//g' \
		-e 's/sbyte\s*\*/string/g' \
		-e 's/int \(RL_SHADER_LOC\)/rlShaderLocationIndex \1/g' \
		-e '/= ;$$/d' $@ \
		-e '/const U*IntPtr/d' \
		-e '/(nu*int)/d' \
		-e '/ReadOnlySpan</d'

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) $(CFLAGS) -shared -o $@ $^ $(LDLIBS)

.PHONY: clean distclean
clean:

distclean: clean
	$(RM) RlGl.cs
